"""Registry of ownable kit Components (CLI + docs).

shadcn-style: ``uxcompose add login`` copies the module into the app.
The app owns the file. The library keeps the source of truth.
"""

from __future__ import annotations

from typing import TypedDict


class KitEntry(TypedDict):
    name: str
    module: str
    stem: str
    exports: list[str]
    description: str
    css: bool
    page: bool


CATALOG: dict[str, KitEntry] = {
    "login": {
        "name": "Login",
        "module": "ux_compose.kit.login",
        "stem": "login",
        "exports": ["Login", "AuthDecision"],
        "description": "Sign-in / sign-up card. Mode tabs are tablist + tabpanel. Reveal attaches. Submit is a Cap.",
        "css": False,
        "page": True,
    },
    "tabs": {
        "name": "Tabs",
        "module": "ux_compose.kit.tabs",
        "stem": "tabs",
        "exports": ["Tabs"],
        "description": "Segmented tabs. Namespaced {id}-tab-{k} / {id}-p-{k}. Inactive panels stay hidden. Select is open mint.",
        "css": False,
        "page": True,
    },
    "accordion": {
        "name": "Accordion",
        "module": "ux_compose.kit.accordion",
        "stem": "accordion",
        "exports": ["Accordion"],
        "description": "Open ids as a MorphState tuple. Panel ids are {id}-p-{key}. Several panels may be open.",
        "css": False,
        "page": True,
    },
    "dropdown": {
        "name": "Dropdown",
        "module": "ux_compose.kit.dropdown",
        "stem": "dropdown",
        "exports": ["Dropdown"],
        "description": "Menu is presence. Value is a named key.",
        "css": False,
        "page": True,
    },
    "dialog": {
        "name": "Dialog",
        "module": "ux_compose.kit.dialog",
        "stem": "dialog",
        "exports": ["Dialog"],
        "description": "Public ask, Cap-protected confirm. Override on_confirm().",
        "css": False,
        "page": True,
    },
    "sheet": {
        "name": "Sheet",
        "module": "ux_compose.kit.sheet",
        "stem": "sheet",
        "exports": ["Sheet"],
        "description": "Edge panel. Close / Done accept swipe.right. No root swipe.",
        "css": False,
        "page": True,
    },
    "toast": {
        "name": "Toast",
        "module": "ux_compose.kit.toast",
        "stem": "toast",
        "exports": ["Toast"],
        "description": "Server list is authority. Push is open mint; Intent POST must send html-unescaped sealed-args from data-channel-args.",
        "css": False,
        "page": True,
    },
    "command": {
        "name": "Command",
        "module": "ux_compose.kit.command",
        "stem": "command",
        "exports": ["Command"],
        "description": "Command palette. Query attaches. Sign out spends auth.logout. Override on_run().",
        "css": False,
        "page": True,
    },
    "table": {
        "name": "Table",
        "module": "ux_compose.kit.table",
        "stem": "table",
        "exports": ["Table"],
        "description": "Sort key MorphState, selection RefState. Row checkbox is focusable; bind is on the checkbox, not the row. Header toggle_all is not a row click. Archive is a Cap.",
        "css": False,
        "page": True,
    },
    "pagination": {
        "name": "Pagination",
        "module": "ux_compose.kit.pagination",
        "stem": "pagination",
        "exports": ["Pagination"],
        "description": "Opaque page keys. Windowed numbers, not one button per page.",
        "css": False,
        "page": True,
    },
    "combobox": {
        "name": "Combobox",
        "module": "ux_compose.kit.combobox",
        "stem": "combobox",
        "exports": ["Combobox"],
        "description": "Type to filter, then pick. Query attaches on morph. Ids follow {id}-form / {id}-opt-n.",
        "css": False,
        "page": True,
    },
    "sidebar": {
        "name": "Sidebar",
        "module": "ux_compose.kit.sidebar",
        "stem": "sidebar",
        "exports": ["Sidebar"],
        "description": "Collapsible rail. Active key is MorphState.",
        "css": False,
        "page": True,
    },
    "breadcrumb": {
        "name": "Breadcrumb",
        "module": "ux_compose.kit.breadcrumb",
        "stem": "breadcrumb",
        "exports": ["Breadcrumb"],
        "description": "Trail of named crumbs. Walking back is public.",
        "css": False,
        "page": True,
    },
    "stepper": {
        "name": "Stepper",
        "module": "ux_compose.kit.stepper",
        "stem": "stepper",
        "exports": ["Stepper"],
        "description": "Named steps. Finish spends stepper.finish.",
        "css": False,
        "page": True,
    },
    "carousel": {
        "name": "Carousel",
        "module": "ux_compose.kit.carousel",
        "stem": "carousel",
        "exports": ["Carousel"],
        "description": "Named slides. Overlay prev/next. Sliding pip coalesces on morph.",
        "css": False,
        "page": True,
    },
    "calendar": {
        "name": "Calendar",
        "module": "ux_compose.kit.calendar",
        "stem": "calendar",
        "exports": ["Calendar"],
        "description": "Month grid. role=grid; selected day aria-selected. Day is a name. Override on_pick().",
        "css": False,
        "page": True,
    },
    "select": {
        "name": "Select",
        "module": "ux_compose.kit.select",
        "stem": "select",
        "exports": ["Select"],
        "description": "Grouped options. Label for ↔ trigger id. Value is a name.",
        "css": False,
        "page": True,
    },
    "otp": {
        "name": "Otp",
        "module": "ux_compose.kit.otp",
        "stem": "otp",
        "exports": ["Otp"],
        "description": "Six digits attach. Verify spends auth.otp.",
        "css": False,
        "page": True,
    },
    "plans": {
        "name": "Plans",
        "module": "ux_compose.kit.plans",
        "stem": "plans",
        "exports": ["Plans"],
        "description": "Radio group of named plans. role=radio aria-checked. Override on_choose().",
        "css": False,
        "page": True,
    },
    "actionsheet": {
        "name": "ActionSheet",
        "module": "ux_compose.kit.actionsheet",
        "stem": "actionsheet",
        "exports": ["ActionSheet"],
        "description": "Bottom sheet. Autofocus on open. Handle swipe-down dismisses. Rows stay click.",
        "css": False,
        "page": True,
    },
    "contextmenu": {
        "name": "ContextMenu",
        "module": "ux_compose.kit.contextmenu",
        "stem": "contextmenu",
        "exports": ["ContextMenu"],
        "description": "Click or longpress. aria-controls the menu. Floating panel, not a native list.",
        "css": False,
        "page": True,
    },
    "typeahead": {
        "name": "Typeahead",
        "module": "ux_compose.kit.typeahead",
        "stem": "typeahead",
        "exports": ["Typeahead"],
        "description": "Live filter on input delay:. The field is the control.",
        "css": False,
        "page": True,
    },
    "pullrefresh": {
        "name": "PullRefresh",
        "module": "ux_compose.kit.pullrefresh",
        "stem": "pullrefresh",
        "exports": ["PullRefresh"],
        "description": "Vertical swipe synthesizer. Refresh control accepts swipe.down.",
        "css": False,
        "page": True,
    },
    "drawer": {
        "name": "Drawer",
        "module": "ux_compose.kit.drawer",
        "stem": "drawer",
        "exports": ["Drawer"],
        "description": "Sheet alias — same Host, right edge. Not a second overlay Host.",
        "css": False,
        "page": True,
    },
    "navbar": {
        "name": "Navbar",
        "module": "ux_compose.kit.navbar",
        "stem": "navbar",
        "exports": ["Navbar"],
        "description": "Primary nav landmark. Desktop and mobile menus are two trees.",
        "css": False,
        "page": True,
    },
    "navmenu": {
        "name": "NavMenu",
        "module": "ux_compose.kit.navmenu",
        "stem": "navmenu",
        "exports": ["NavMenu"],
        "description": "Disclosure menu of named destinations. Opening is public.",
        "css": False,
        "page": True,
    },
    "usermenu": {
        "name": "UserMenu",
        "module": "ux_compose.kit.usermenu",
        "stem": "usermenu",
        "exports": ["UserMenu"],
        "description": "Identity menu. Sign-out spends auth.logout.",
        "css": False,
        "page": True,
    },
    "popover": {
        "name": "Popover",
        "module": "ux_compose.kit.popover",
        "stem": "popover",
        "exports": ["Popover"],
        "description": "Non-modal dialog anchored to a trigger. Escape dismisses.",
        "css": False,
        "page": True,
    },
    "tooltip": {
        "name": "Tooltip",
        "module": "ux_compose.kit.tooltip",
        "stem": "tooltip",
        "exports": ["Tooltip"],
        "description": "role=tooltip described-by hint. Not a modal.",
        "css": False,
        "page": True,
    },
    "alertdialog": {
        "name": "AlertDialog",
        "module": "ux_compose.kit.alertdialog",
        "stem": "alertdialog",
        "exports": ["AlertDialog"],
        "description": "Interrupting confirm. role=alertdialog. Escape/scrim do not dismiss; Keep/Delete choose. Confirm spends a Cap.",
        "css": False,
        "page": True,
    },
    "formlayout": {
        "name": "FormLayout",
        "module": "ux_compose.kit.formlayout",
        "stem": "formlayout",
        "exports": ["FormLayout"],
        "description": "Labeled fields. label for ↔ id. Submit spends form.submit.",
        "css": False,
        "page": True,
    },
    "fieldset": {
        "name": "Fieldset",
        "module": "ux_compose.kit.fieldset",
        "stem": "fieldset",
        "exports": ["Fieldset"],
        "description": "Native fieldset + legend radiogroup. Value is a name.",
        "css": False,
        "page": True,
    },
    "datepicker": {
        "name": "DatePicker",
        "module": "ux_compose.kit.datepicker",
        "stem": "datepicker",
        "exports": ["DatePicker"],
        "description": "Labeled day key + month grid (row/gridcell). Day is a name, not a quantity.",
        "css": False,
        "page": True,
    },
    "switch": {
        "name": "Switch",
        "module": "ux_compose.kit.switch",
        "stem": "switch",
        "exports": ["Switch"],
        "description": "role=switch. Boolean MorphState. Flipping is public.",
        "css": False,
        "page": True,
    },
    "card": {
        "name": "Card",
        "module": "ux_compose.kit.card",
        "stem": "card",
        "exports": ["Card"],
        "description": "Titled article with a public action.",
        "css": False,
        "page": True,
    },
    "emptystate": {
        "name": "EmptyState",
        "module": "ux_compose.kit.emptystate",
        "stem": "emptystate",
        "exports": ["EmptyState"],
        "description": "Void region + CTA. Filling is public Morph.",
        "css": False,
        "page": True,
    },
    "stats": {
        "name": "Stats",
        "module": "ux_compose.kit.stats",
        "stem": "stats",
        "exports": ["Stats"],
        "description": "Named metrics on RefState. dirty is the morph clock.",
        "css": False,
        "page": True,
    },
    "alert": {
        "name": "Alert",
        "module": "ux_compose.kit.alert",
        "stem": "alert",
        "exports": ["Alert"],
        "description": "Inline role=alert. Dismiss is public.",
        "css": False,
        "page": True,
    },
    "banner": {
        "name": "Banner",
        "module": "ux_compose.kit.banner",
        "stem": "banner",
        "exports": ["Banner"],
        "description": "Page-level region notice. Not role=alert.",
        "css": False,
        "page": True,
    },
    "progress": {
        "name": "Progress",
        "module": "ux_compose.kit.progress",
        "stem": "progress",
        "exports": ["Progress"],
        "description": "progressbar. Magnitude is RefState, never MorphState.",
        "css": False,
        "page": True,
    },
    "skeleton": {
        "name": "Skeleton",
        "module": "ux_compose.kit.skeleton",
        "stem": "skeleton",
        "exports": ["Skeleton"],
        "description": "Loading placeholder. aria-busy. Bars are aria-hidden.",
        "css": False,
        "page": True,
    },
    "hero": {
        "name": "Hero",
        "module": "ux_compose.kit.hero",
        "stem": "hero",
        "exports": ["Hero"],
        "description": "Landing band with a public CTA.",
        "css": False,
        "page": True,
    },
    "footer": {
        "name": "Footer",
        "module": "ux_compose.kit.footer",
        "stem": "footer",
        "exports": ["Footer"],
        "description": "contentinfo landmark. Named links, aria-current.",
        "css": False,
        "page": True,
    },
    "cta": {
        "name": "Cta",
        "module": "ux_compose.kit.cta",
        "stem": "cta",
        "exports": ["Cta"],
        "description": "Titled call to action. Demo act is public.",
        "css": False,
        "page": True,
    },
    "avatar": {
        "name": "Avatar",
        "module": "ux_compose.kit.avatar",
        "stem": "avatar",
        "exports": ["Avatar"],
        "description": "Initials with role=img aria-label.",
        "css": False,
        "page": True,
    },
    "badge": {
        "name": "Badge",
        "module": "ux_compose.kit.badge",
        "stem": "badge",
        "exports": ["Badge"],
        "description": "Named status chips. aria-pressed on the selected chip.",
        "css": False,
        "page": True,
    },
    "hovercard": {
        "name": "HoverCard",
        "module": "ux_compose.kit.hovercard",
        "stem": "hovercard",
        "exports": ["HoverCard"],
        "description": "Non-modal preview dialog. Escape dismisses.",
        "css": False,
        "page": True,
    },
    "searchbar": {
        "name": "SearchBar",
        "module": "ux_compose.kit.searchbar",
        "stem": "searchbar",
        "exports": ["SearchBar"],
        "description": "Labeled search field. Hits are a listbox.",
        "css": False,
        "page": True,
    },
    "fileupload": {
        "name": "FileUpload",
        "module": "ux_compose.kit.fileupload",
        "stem": "fileupload",
        "exports": ["FileUpload"],
        "description": "Labeled file control. Names live on RefState. Demo names sketch.png; Host wires a real upload.",
        "css": False,
        "page": True,
    },
    "tagsinput": {
        "name": "TagsInput",
        "module": "ux_compose.kit.tagsinput",
        "stem": "tagsinput",
        "exports": ["TagsInput"],
        "description": "Named chips + labeled field. List is RefState.",
        "css": False,
        "page": True,
    },
    "multiselect": {
        "name": "MultiSelect",
        "module": "ux_compose.kit.multiselect",
        "stem": "multiselect",
        "exports": ["MultiSelect"],
        "description": "Multi listbox. Select-all is not a row toggle.",
        "css": False,
        "page": True,
    },
    "descriptionlist": {
        "name": "DescriptionList",
        "module": "ux_compose.kit.descriptionlist",
        "stem": "descriptionlist",
        "exports": ["DescriptionList"],
        "description": "dl/dt/dd facts. Not a data table.",
        "css": False,
        "page": True,
    },
    "featuregrid": {
        "name": "FeatureGrid",
        "module": "ux_compose.kit.featuregrid",
        "stem": "featuregrid",
        "exports": ["FeatureGrid"],
        "description": "Named tiles. Active key is MorphState.",
        "css": False,
        "page": True,
    },
    "testimonials": {
        "name": "Testimonials",
        "module": "ux_compose.kit.testimonials",
        "stem": "testimonials",
        "exports": ["Testimonials"],
        "description": "Named quotes. which is a key, not a quantity.",
        "css": False,
        "page": True,
    },
    "newsletter": {
        "name": "Newsletter",
        "module": "ux_compose.kit.newsletter",
        "stem": "newsletter",
        "exports": ["Newsletter"],
        "description": "Labeled email. Subscribe spends list.subscribe.",
        "css": False,
        "page": True,
    },
    "bottomnav": {
        "name": "BottomNav",
        "module": "ux_compose.kit.bottomnav",
        "stem": "bottomnav",
        "exports": ["BottomNav"],
        "description": "Mobile sections landmark. aria-current on the active item.",
        "css": False,
        "page": True,
    },
    "separator": {
        "name": "Separator",
        "module": "ux_compose.kit.separator",
        "stem": "separator",
        "exports": ["Separator"],
        "description": "Composite labeled rule. Not a bare hr atom.",
        "css": False,
        "page": True,
    },
    "slider": {
        "name": "Slider",
        "module": "ux_compose.kit.slider",
        "stem": "slider",
        "exports": ["Slider"],
        "description": "Labeled range. Magnitude is RefState. role=slider.",
        "css": False,
        "page": True,
    },
    "menubar": {
        "name": "Menubar",
        "module": "ux_compose.kit.menubar",
        "stem": "menubar",
        "exports": ["Menubar"],
        "description": "APG menubar. Submenus aria-haspopup/expanded/controls. Inactive menus stay hidden (ids stay in the tree).",
        "css": False,
        "page": True,
    },
    "toolbar": {
        "name": "Toolbar",
        "module": "ux_compose.kit.toolbar",
        "stem": "toolbar",
        "exports": ["Toolbar"],
        "description": "APG toolbar. Groups + separators. Last command aria-current (not pressed). Caps stay off.",
        "css": False,
        "page": True,
    },
    "togglegroup": {
        "name": "ToggleGroup",
        "module": "ux_compose.kit.togglegroup",
        "stem": "togglegroup",
        "exports": ["ToggleGroup"],
        "description": "Exclusive radiogroup. Value is a name. Not Tabs (no panels).",
        "css": False,
        "page": True,
    },
    "spinbutton": {
        "name": "SpinButton",
        "module": "ux_compose.kit.spinbutton",
        "stem": "spinbutton",
        "exports": ["SpinButton"],
        "description": "APG spinbutton. Magnitude is RefState. Label for ↔ id. Not Stepper.",
        "css": False,
        "page": True,
    },
    "themeswitch": {
        "name": "ThemeSwitch",
        "module": "ux_compose.kit.themeswitch",
        "stem": "themeswitch",
        "exports": ["ThemeSwitch"],
        "description": "Named theme radiogroup (light/dark/system). Not a boolean switch.",
        "css": False,
        "page": True,
    },
    "filterbar": {
        "name": "FilterBar",
        "module": "ux_compose.kit.filterbar",
        "stem": "filterbar",
        "exports": ["FilterBar"],
        "description": "Labeled query + named filter radiogroup. Hits filter in place.",
        "css": False,
        "page": True,
    },
    "chat": {
        "name": "Chat",
        "module": "ux_compose.kit.chat",
        "stem": "chat",
        "exports": ["Chat"],
        "description": "Thread log (role=log). Composer is labeled. Send is public.",
        "css": False,
        "page": True,
    },
    "questionnaire": {
        "name": "Questionnaire",
        "module": "ux_compose.kit.questionnaire",
        "stem": "questionnaire",
        "exports": ["Questionnaire"],
        "description": "Named questions as fieldset radiogroups. Submit spends form.submit.",
        "css": False,
        "page": True,
    },
}


def list_components() -> list[KitEntry]:
    return list(CATALOG.values())


def resolve(name: str) -> KitEntry:
    raw = name.strip().lower()
    key = raw.replace("-", "_")
    compact = key.replace("_", "")
    if key in CATALOG:
        return CATALOG[key]
    if compact in CATALOG:
        return CATALOG[compact]
    for k, meta in CATALOG.items():
        if meta["name"].lower() == key or meta["name"].lower() == compact:
            return meta
        if meta["stem"] == key or meta["stem"] == compact:
            return meta
    raise KeyError(key)
